default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: docker
  password: docker
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: mini_test_skip_development
  other:
    <<: *default
    database: other_development

test:
  primary:
    <<: *default
    database: mini_test_skip_test
  other:
    <<: *default
    database: other_test

production:
  primary:
    <<: *default
    database: mini_test_skip_production
  other:
    <<: *default
    database: other_production

